# Generated by Django 5.2.14 on 2026-05-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Cover",
            new_name="cover",
        ),
    ]
