# Generated by Django 5.2.14 on 2026-05-13 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0002_rename_cover_book_cover"),
        ("borrowing_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("borrow_date__lt", models.F("expected_return_date"))
                ),
                name="borrow_date_before_expected_return_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(("borrow_date__lt", models.F("actual_return_date"))),
                name="borrow_date_before_actual_return_date",
            ),
        ),
    ]
